#!/bin/sh
# Copyright © 2012 the Minima Authors under the MIT license. See AUTHORS for the list of authors.

objs=$(echo _work/*.o |
	sed -e 's;_work/main.o;;' -e 's;_work/SDLMain.o;;')

tests=$(echo game/test_*.cpp)

if [ "$tests" = 'game/test_*.cpp' ]; then
	echo No tests to run.
	exit
fi

for t in $tests; {
	name=$(echo $t | sed -E 's/([a-zA-Z0-9_]+)\.cpp/\1/')
	echo Running $name
	runt $t
	"$@" -o $name $t.test.cpp $objs
	./$name || echo Please fix that.
	rm $t.test.cpp
	[ -e $name ] && rm $name
}
